export type { createCalendarEvent } from './calendar.interfaces';
export type { MulterRequest } from './multer.interfaces';
export type {
  ChatMessage,
  ChatConversation,
  ChatRequest,
  ChatResponse,
  ChatSettings,
  StreamChatRequest,
  ChatHistory,
  ChatError,
} from './chat.interfaces';

// Tipos de base de datos
export type {
  User,
  Conversation,
  Message,
  CalendarEvent,
  CalendarAttendee,
  PdfDocument,
  ActivityLog,
  SystemConfig,
  ConversationWithMessages,
  CalendarEventWithAttendees,
  UserWithRelations,
  CreateUserData,
  CreateConversationData,
  CreateMessageData,
  CreateCalendarEventData,
  CreatePdfDocumentData,
  CreateActivityLogData,
  UpdateConversationData,
  UpdateCalendarEventData,
  UpdatePdfDocumentData,
  PaginationOptions,
  ConversationFilters,
  CalendarEventFilters,
  PdfDocumentFilters,
  ActivityLogFilters,
  PaginatedResponse,
  ChatStats,
  CalendarStats,
  PdfStats,
  MessageRole,
  ZapierStatus,
  ProcessingStatus,
  ActivityModule,
  ConfigType,
} from './database.interfaces';
